#!/usr/bin/env python
# encoding: utf-8

name = "harris_butane"
shortDesc = ""
longDesc = """

"""
autoGenerated=False
entry(
    index = 127,
    label = "CH2O(9) + OH(15) <=> H2O(8) + HCO(19)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(197815,'cm^3/(mol*s)'), n=2.64456, Ea=(-10.6933,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.07772, dn = +|- 0.00983322, dEa = +|- 0.053512 kJ/mol"""),
)

entry(
    index = 180,
    label = "CH(3) + H2(13) <=> CH2(23) + H(14)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(7.04035e+07,'cm^3/(mol*s)'), n=1.88414, Ea=(67.6004,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.15244, dn = +|- 0.0186405, dEa = +|- 0.101441 kJ/mol"""),
)

entry(
    index = 247,
    label = "butane(1) + OH(15) <=> H2O(8) + SC4H9(183)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(16601.4,'cm^3/(mol*s)'), n=2.75625, Ea=(-8.49166,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.07725, dn = +|- 0.00977586, dEa = +|- 0.0531999 kJ/mol"""),
)

entry(
    index = 288,
    label = "butane(1) + OH(15) <=> H2O(8) + PC4H9(182)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4762.94,'cm^3/(mol*s)'), n=2.89814, Ea=(-4.40641,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06097, dn = +|- 0.00777564, dEa = +|- 0.0423148 kJ/mol"""),
)

entry(
    index = 290,
    label = "butane(1) + HO2(16) <=> H2O2(17) + PC4H9(182)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.458014,'cm^3/(mol*s)'), n=3.78193, Ea=(64.2847,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06651, dn = +|- 0.00846012, dEa = +|- 0.0460397 kJ/mol"""),
)

entry(
    index = 294,
    label = "CH2O(9) + PC4H9(182) <=> butane(1) + HCO(19)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.44572,'cm^3/(mol*s)'), n=3.34308, Ea=(27.9403,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.08504, dn = +|- 0.0107224, dEa = +|- 0.0583511 kJ/mol"""),
)

entry(
    index = 324,
    label = "S(229) <=> S(225)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.05219e+09,'s^-1'), n=0.437587, Ea=(64.2353,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.08828, dn = +|- 0.0111145, dEa = +|- 0.0604846 kJ/mol"""),
)

entry(
    index = 325,
    label = "S(225) <=> S(244)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(5.56457e+10,'s^-1'), n=0.743989, Ea=(171.693,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.1028, dn = +|- 0.0128559, dEa = +|- 0.0699611 kJ/mol"""),
)

entry(
    index = 326,
    label = "S(225) <=> S(238)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(9.82352e+09,'s^-1'), n=0.726099, Ea=(87.0666,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06332, dn = +|- 0.00806652, dEa = +|- 0.0438977 kJ/mol"""),
)

entry(
    index = 370,
    label = "CH3CHO(35) + SC4H9(183) <=> CH2CHO(21) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.163973,'cm^3/(mol*s)'), n=3.34314, Ea=(32.3035,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.08323, dn = +|- 0.010503, dEa = +|- 0.057157 kJ/mol"""),
)

entry(
    index = 371,
    label = "CH3CHO(35) + PC4H9(182) <=> butane(1) + CH2CHO(21)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.573559,'cm^3/(mol*s)'), n=3.28661, Ea=(31.1286,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.11021, dn = +|- 0.0137356, dEa = +|- 0.0747485 kJ/mol"""),
)

entry(
    index = 585,
    label = "CH2(23) + C3H6(12) <=> CH3(18) + C3H5-A(94)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(71.7168,'cm^3/(mol*s)'), n=3.56192, Ea=(19.9111,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04642, dn = +|- 0.00596139, dEa = +|- 0.0324417 kJ/mol"""),
)

entry(
    index = 591,
    label = "CH3CHO(35) + C3H5-A(94) <=> C3H6(12) + CH3CO(20)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.54627e-05,'cm^3/(mol*s)'), n=5.28333, Ea=(41.8104,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 2.99386, dn = +|- 0.144066, dEa = +|- 0.784004 kJ/mol"""),
)

entry(
    index = 650,
    label = "HO2(16) + C4H8(748) <=> O2(2) + SC4H9(183)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.24074,'cm^3/(mol*s)'), n=3.13025, Ea=(-34.5412,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.17128, dn = +|- 0.0207709, dEa = +|- 0.113034 kJ/mol"""),
)

entry(
    index = 655,
    label = "HO2(16) + C4H8(748) <=> O2(2) + PC4H9(182)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.358,'cm^3/(mol*s)'), n=3.14973, Ea=(-32.8382,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.15084, dn = +|- 0.0184574, dEa = +|- 0.100445 kJ/mol"""),
)

entry(
    index = 739,
    label = "C4H8(188) + CH2CHO(21) <=> CH3CHO(35) + C4H7(190)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.75479,'cm^3/(mol*s)'), n=3.46517, Ea=(33.4573,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03834, dn = +|- 0.00494262, dEa = +|- 0.0268976 kJ/mol"""),
)

entry(
    index = 748,
    label = "HCO(19) + C4H8(189) <=> CH2O(9) + C4H7(190)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(26.9388,'cm^3/(mol*s)'), n=3.5471, Ea=(59.8014,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04299, dn = +|- 0.00553036, dEa = +|- 0.030096 kJ/mol"""),
)

entry(
    index = 749,
    label = "HCO(19) + C4H8(188) <=> CH2O(9) + C4H7(190)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(21.2582,'cm^3/(mol*s)'), n=3.56673, Ea=(51.9784,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.039, dn = +|- 0.00502699, dEa = +|- 0.0273567 kJ/mol"""),
)

entry(
    index = 754,
    label = "C4H8(189) + CH2(23) <=> CH3(18) + C4H7(190)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(16675.7,'cm^3/(mol*s)'), n=2.56103, Ea=(19.0922,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04582, dn = +|- 0.00588551, dEa = +|- 0.0320288 kJ/mol"""),
)

entry(
    index = 894,
    label = "C3H6(12) + S(244) <=> S(787) + C3H5-A(94)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(15.5559,'cm^3/(mol*s)'), n=3.5855, Ea=(295.832,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05677, dn = +|- 0.00725461, dEa = +|- 0.0394793 kJ/mol"""),
)

entry(
    index = 985,
    label = "HO2(16) + C2H4O(703) <=> O2(2) + C2H5O(49)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(12.9689,'cm^3/(mol*s)'), n=3.08189, Ea=(-25.0776,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.18103, dn = +|- 0.0218603, dEa = +|- 0.118963 kJ/mol"""),
)

entry(
    index = 1003,
    label = "HO2(16) + C4H7(191) <=> O2(2) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.983651,'cm^3/(mol*s)'), n=3.13392, Ea=(-32.1994,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.17466, dn = +|- 0.0211489, dEa = +|- 0.115091 kJ/mol"""),
)

entry(
    index = 1026,
    label = "CH3CHO(35) + C4H7(191) <=> C4H8(188) + CH2CHO(21)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.0625764,'cm^3/(mol*s)'), n=3.26198, Ea=(29.6708,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.12094, dn = +|- 0.0149999, dEa = +|- 0.0816287 kJ/mol"""),
)

entry(
    index = 1290,
    label = "C3H6O3(73) + PC4H9(182) <=> butane(1) + S(911)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.0684738,'cm^3/(mol*s)'), n=3.25988, Ea=(33.6341,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.12117, dn = +|- 0.0150262, dEa = +|- 0.0817721 kJ/mol"""),
)

entry(
    index = 1301,
    label = "C3H6O3(73) + HO2(16) <=> H2O2(17) + S(911)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.109332,'cm^3/(mol*s)'), n=3.65195, Ea=(63.1235,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05136, dn = +|- 0.00658052, dEa = +|- 0.035811 kJ/mol"""),
)

entry(
    index = 1509,
    label = "CH3OH(30) + C4H7(192) <=> C4H8(188) + CH3O(31)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(3.79281,'cm^3/(mol*s)'), n=3.38163, Ea=(10.986,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.11457, dn = +|- 0.0142502, dEa = +|- 0.0775488 kJ/mol"""),
)

entry(
    index = 1638,
    label = "CH2O(9) + C2H5O2(47) <=> C2H6O2(48) + HCO(19)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.09084,'cm^3/(mol*s)'), n=3.67575, Ea=(41.5414,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04965, dn = +|- 0.00636631, dEa = +|- 0.0346452 kJ/mol"""),
)

entry(
    index = 1646,
    label = "butane(1) + C2H5O2(47) <=> C2H6O2(48) + SC4H9(183)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.115711,'cm^3/(mol*s)'), n=3.80169, Ea=(59.4575,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06707, dn = +|- 0.0085288, dEa = +|- 0.0464134 kJ/mol"""),
)

entry(
    index = 1656,
    label = "C2H6O2(48) + C4H7(191) <=> C4H8(188) + C2H5O2(47)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.387437,'cm^3/(mol*s)'), n=3.13363, Ea=(6.37901,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.18913, dn = +|- 0.0227575, dEa = +|- 0.123845 kJ/mol"""),
)

entry(
    index = 213,
    label = "HO2(16) + C2H5(33) <=> H2O2(17) + C2H4(11)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.414735,'cm^3/(mol*s)'), n=3.69855, Ea=(73.8711,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05553, dn = +|- 0.00710038, dEa = +|- 0.03864 kJ/mol"""),
)

entry(
    index = 410,
    label = "CH3(18) + PC4H9(182) <=> CH4(10) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(54.6358,'cm^3/(mol*s)'), n=3.25821, Ea=(43.182,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.11674, dn = +|- 0.0145056, dEa = +|- 0.078939 kJ/mol"""),
)

entry(
    index = 419,
    label = "HO2(16) + CH2CHO(21) <=> H2O2(17) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.4849,'cm^3/(mol*s)'), n=3.54286, Ea=(37.6165,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04117, dn = +|- 0.00530039, dEa = +|- 0.0288445 kJ/mol"""),
)

entry(
    index = 420,
    label = "HO2(16) + SC4H9(183) <=> H2O2(17) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.640017,'cm^3/(mol*s)'), n=3.72313, Ea=(65.9604,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06662, dn = +|- 0.00847356, dEa = +|- 0.0461128 kJ/mol"""),
)

entry(
    index = 422,
    label = "HO2(16) + SC4H9(183) <=> H2O2(17) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.257838,'cm^3/(mol*s)'), n=3.71819, Ea=(74.0289,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05985, dn = +|- 0.007637, dEa = +|- 0.0415603 kJ/mol"""),
)

entry(
    index = 459,
    label = "CH3(18) + SC4H9(183) <=> CH4(10) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(95.8155,'cm^3/(mol*s)'), n=3.27255, Ea=(44.6643,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.10885, dn = +|- 0.0135752, dEa = +|- 0.0738759 kJ/mol"""),
)

entry(
    index = 464,
    label = "CH3(18) + CH2CHO(21) <=> CH4(10) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(8394.62,'cm^3/(mol*s)'), n=3.21955, Ea=(29.5288,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.10297, dn = +|- 0.012876, dEa = +|- 0.0700705 kJ/mol"""),
)

entry(
    index = 574,
    label = "CH3O(31) + C3H5-A(94) <=> CH2O(9) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(72.9352,'cm^3/(mol*s)'), n=3.20259, Ea=(79.5529,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.10879, dn = +|- 0.0135681, dEa = +|- 0.073837 kJ/mol"""),
)

entry(
    index = 577,
    label = "C3H5-A(94) + SC4H9(183) <=> C3H6(12) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.0825,'cm^3/(mol*s)'), n=3.41486, Ea=(85.5728,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03933, dn = +|- 0.00506834, dEa = +|- 0.0275817 kJ/mol"""),
)

entry(
    index = 578,
    label = "C3H5-A(94) + PC4H9(182) <=> C3H6(12) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.32242,'cm^3/(mol*s)'), n=3.41386, Ea=(82.589,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04327, dn = +|- 0.00556484, dEa = +|- 0.0302836 kJ/mol"""),
)

entry(
    index = 581,
    label = "CH2CHO(21) + C3H5-A(94) <=> CH2CO(24) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(69.6641,'cm^3/(mol*s)'), n=3.33308, Ea=(65.3002,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03484, dn = +|- 0.00449968, dEa = +|- 0.0244871 kJ/mol"""),
)

entry(
    index = 586,
    label = "CH2O(9) + C3H5-A(94) <=> HCO(19) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(144.338,'cm^3/(mol*s)'), n=3.41995, Ea=(63.6639,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04529, dn = +|- 0.00581974, dEa = +|- 0.0316708 kJ/mol"""),
)

entry(
    index = 714,
    label = "C2H5(33) + C4H7(190) <=> C2H4(11) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(3.4931,'cm^3/(mol*s)'), n=3.41082, Ea=(96.9206,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05828, dn = +|- 0.0074424, dEa = +|- 0.0405013 kJ/mol"""),
)

entry(
    index = 720,
    label = "CH2CHO(21) + C4H7(190) <=> CH2CO(24) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(22.7328,'cm^3/(mol*s)'), n=3.3669, Ea=(67.4533,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.026, dn = +|- 0.00337172, dEa = +|- 0.0183488 kJ/mol"""),
)

entry(
    index = 722,
    label = "CH2CHO(21) + C4H7(190) <=> CH2CO(24) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(15.8777,'cm^3/(mol*s)'), n=3.32153, Ea=(70.501,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03322, dn = +|- 0.00429399, dEa = +|- 0.0233677 kJ/mol"""),
)

entry(
    index = 725,
    label = "CH3O(31) + C4H7(190) <=> CH2O(9) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(22.9646,'cm^3/(mol*s)'), n=3.23567, Ea=(81.3601,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.09675, dn = +|- 0.0121334, dEa = +|- 0.0660293 kJ/mol"""),
)

entry(
    index = 726,
    label = "C4H7(190) + SC4H9(183) <=> C4H8(189) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.296115,'cm^3/(mol*s)'), n=3.3987, Ea=(89.9554,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04292, dn = +|- 0.00552099, dEa = +|- 0.030045 kJ/mol"""),
)

entry(
    index = 728,
    label = "C4H7(190) + SC4H9(183) <=> C4H8(188) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.96948,'cm^3/(mol*s)'), n=3.42325, Ea=(93.6281,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03491, dn = +|- 0.0045088, dEa = +|- 0.0245367 kJ/mol"""),
)

entry(
    index = 793,
    label = "HO2(16) + C4H7(190) <=> H2O2(17) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.215461,'cm^3/(mol*s)'), n=3.70118, Ea=(75.9667,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05676, dn = +|- 0.00725372, dEa = +|- 0.0394745 kJ/mol"""),
)

entry(
    index = 794,
    label = "CH3(18) + C4H7(190) <=> CH4(10) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(84.9677,'cm^3/(mol*s)'), n=3.24126, Ea=(53.1278,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.1376, dn = +|- 0.0169381, dEa = +|- 0.0921765 kJ/mol"""),
)

entry(
    index = 795,
    label = "C4H7(190) + C4H7(190) <=> C4H6(194) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(3.52853,'cm^3/(mol*s)'), n=3.44008, Ea=(102.154,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04559, dn = +|- 0.00585718, dEa = +|- 0.0318745 kJ/mol"""),
)

entry(
    index = 800,
    label = "OH(15) + C4H7(190) <=> H2O(8) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2580.23,'cm^3/(mol*s)'), n=2.85695, Ea=(1.74945,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.08288, dn = +|- 0.0104613, dEa = +|- 0.0569301 kJ/mol"""),
)

entry(
    index = 916,
    label = "OH(15) + S(777) <=> H2O(8) + S(252)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2010.28,'cm^3/(mol*s)'), n=2.54372, Ea=(-16.598,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.10515, dn = +|- 0.0131356, dEa = +|- 0.0714835 kJ/mol"""),
)

entry(
    index = 1103,
    label = "CH3O2(45) + CH2CHO(21) <=> CH3O2H(46) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.95844,'cm^3/(mol*s)'), n=3.57604, Ea=(40.8361,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04011, dn = +|- 0.00516623, dEa = +|- 0.0281145 kJ/mol"""),
)

entry(
    index = 1287,
    label = "C3H6O3(73) + SC4H9(183) <=> C3H5O3(72) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.129642,'cm^3/(mol*s)'), n=3.27017, Ea=(9.935,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.12079, dn = +|- 0.0149821, dEa = +|- 0.0815322 kJ/mol"""),
)

entry(
    index = 1288,
    label = "C3H6O3(73) + PC4H9(182) <=> C3H5O3(72) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.622075,'cm^3/(mol*s)'), n=3.234, Ea=(8.42671,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.14673, dn = +|- 0.017988, dEa = +|- 0.09789 kJ/mol"""),
)

entry(
    index = 1289,
    label = "C3H6O3(73) + SC4H9(183) <=> S(911) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.0239703,'cm^3/(mol*s)'), n=3.32159, Ea=(30.5839,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.08608, dn = +|- 0.0108486, dEa = +|- 0.0590378 kJ/mol"""),
)

entry(
    index = 1326,
    label = "CH2CHO(21) + C3H5O3(72) <=> CH2CO(24) + C3H6O3(73)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.3182,'cm^3/(mol*s)'), n=3.53526, Ea=(37.7687,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03231, dn = +|- 0.00417838, dEa = +|- 0.0227386 kJ/mol"""),
)

entry(
    index = 1522,
    label = "CH3O(31) + C2H5(33) <=> CH3OH(30) + C2H4(11)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(5.51335,'cm^3/(mol*s)'), n=3.2534, Ea=(30.9649,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.1009, dn = +|- 0.0126287, dEa = +|- 0.0687252 kJ/mol"""),
)

entry(
    index = 1532,
    label = "CH3O(31) + C3H5O(129) <=> CH3OH(30) + C3H4O(74)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.302491,'cm^3/(mol*s)'), n=3.89121, Ea=(12.4536,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.17316, dn = +|- 0.0209811, dEa = +|- 0.114179 kJ/mol"""),
)

entry(
    index = 1578,
    label = "OCHO(38) + C2H4O(703) <=> HOCHO(40) + CH2CHO(21)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(29.1994,'cm^3/(mol*s)'), n=3.08675, Ea=(4.93895,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06042, dn = +|- 0.0077077, dEa = +|- 0.041945 kJ/mol"""),
)

entry(
    index = 1658,
    label = "CH2CHO(21) + C2H5O2(47) <=> CH2CO(24) + C2H6O2(48)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.314446,'cm^3/(mol*s)'), n=3.58782, Ea=(40.4826,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04318, dn = +|- 0.00555435, dEa = +|- 0.0302266 kJ/mol"""),
)

entry(
    index = 1685,
    label = "C2H5(33) + C2H5O2(47) <=> C2H4(11) + C2H6O2(48)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.0408979,'cm^3/(mol*s)'), n=3.73129, Ea=(77.3142,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05166, dn = +|- 0.00661799, dEa = +|- 0.0360149 kJ/mol"""),
)

entry(
    index = 1714,
    label = "S(223) + butane(1) <=> SC4H9(183) + S(187)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.00407379,'cm^3/(mol*s)'), n=3.86196, Ea=(305.548,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.09269, dn = +|- 0.0116462, dEa = +|- 0.0633782 kJ/mol"""),
)

entry(
    index = 2240,
    label = "HCO(19) + C=CO <=> CH2O(9) + C=C[O]",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(18.8179,'cm^3/(mol*s)'), n=3.32989, Ea=(47.4548,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.11438, dn = +|- 0.0142286, dEa = +|- 0.0774315 kJ/mol"""),
)

entry(
    index = 2303,
    label = "C=C[O] + C2H5(33) <=> C2H4(11) + C=CO",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.674621,'cm^3/(mol*s)'), n=3.56922, Ea=(95.9716,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05138, dn = +|- 0.00658209, dEa = +|- 0.0358195 kJ/mol"""),
)

entry(
    index = 2309,
    label = "C=C[O] + SC4H9(183) <=> C=CO + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.354449,'cm^3/(mol*s)'), n=3.56919, Ea=(84.8408,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04369, dn = +|- 0.00561752, dEa = +|- 0.0305703 kJ/mol"""),
)

entry(
    index = 2422,
    label = "C=C[C]=O + C3H6(12) <=> C3H4O(74) + C3H5-A(94)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(10.9099,'cm^3/(mol*s)'), n=3.30124, Ea=(63.0641,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.10312, dn = +|- 0.012894, dEa = +|- 0.0701685 kJ/mol"""),
)

entry(
    index = 2425,
    label = "C=C[C]=O + C4H8(189) <=> C3H4O(74) + C4H7(190)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(217.589,'cm^3/(mol*s)'), n=3.33249, Ea=(72.6205,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.0909, dn = +|- 0.0114309, dEa = +|- 0.0622066 kJ/mol"""),
)

